services:
    apache:
        build:
            context: ./docker/apache
        volumes:
            - ./project:/var/www/html
            - ./src:/var/www/bundle/src:ro
            - ./tests:/var/www/bundle/tests:ro
            - ./vendor:/var/www/bundle/vendor:rw
            - ./composer.json:/var/www/bundle/composer.json:rw
            - ./composer.lock:/var/www/bundle/composer.lock:rw
            - ./config:/var/www/bundle/config:ro
            - ./phpunit.xml.dist:/var/www/bundle/phpunit.xml.dist:ro
            - ./docker/apache/php.ini:/usr/local/etc/php/conf.d/99-user.ini:ro
            - ~/.composer:/var/www/.composer
        ports:
            - "9310:80"
